services:
  data:
    image: ufavsuwt/resault-date
    build:
      dockerfile: data.dockerfile
  result:
    image: ufavsuwt/resault
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - data
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 12h & wait $$ ! ; nginx -s reload; done & nginx -g \"deamon off;\"'"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./certbot/data:/etc/letsencrypt
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $$ ! ; done'"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencrypt
