services:
  data:
    image: ufavsuwt/resault-date
    build:
      dockerfile: data.dockerfile
  result:
    image: ufavsuwt/resault
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - data
